"""
Django settings for download_shortener_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config # Make sure 'python-decouple' is in your requirements.txt
import pymysql # Make sure 'PyMySQL' is in your requirements.txt
pymysql.install_as_MySQLdb() # This line ensures Django uses PyMySQL for MySQLdb compatibility


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY') # Loaded from .env or cPanel environment variables

# SECURITY WARNING: don't run with debug turned on in production!
# Use config() for DEBUG to control it via environment variables (e.g., in .env or cPanel)
DEBUG = config('DEBUG', default=False, cast=bool) # Set default to False for safety in production

# ALLOWED_HOSTS for production.
# This should be a comma-separated list in your .env or cPanel environment variable.
# Example .env: ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com,cdn.nzdworld.com
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shortener_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'download_shortener_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Assuming you have a 'templates' folder at project root
        'APP_DIRS': True, # This allows Django to find templates within each app's 'templates' directory
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Often useful for local development, remove or comment in production
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'download_shortener_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),         # Loaded from .env or cPanel env var
        'USER': config('DB_USER'),         # Loaded from .env or cPanel env var
        'PASSWORD': config('DB_PASSWORD'),  # Loaded from .env or cPanel env var
        'HOST': config('DB_HOST', default='localhost'), # Loaded from .env or cPanel env var, default to localhost
        'PORT': config('DB_PORT', default='3306'), # Loaded from .env or cPanel env var, default to 3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# STATICFILES_DIRS is for additional *source* directories for static files (e.g., project-wide assets).
# The warning you saw indicates '/home/hypeblog/cdn.nzdworld.com/static' does not exist as a source.
# If you don't have project-specific static files outside of your apps, this can be an empty list.
# If you *do* have such files (e.g., in 'my_url_shortener_project/static/'), then it should point there.
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'static'), # Uncomment this if you have a 'static' folder directly at your project root
]

# STATIC_ROOT is the *destination* directory where 'collectstatic' gathers all static files for production.
# This is the directory your web server (Apache/Nginx via cPanel) serves from.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'