# Generated by Django 4.2.13 on 2025-05-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A descriptive name for this ad unit (e.g., 'Google AdSense 300x250 - Waiting Top')", max_length=100)),
                ('ad_code', models.TextField(help_text='Paste the full HTML/JavaScript ad code here (e.g., AdSense, PropellerAds).')),
                ('location', models.CharField(choices=[('waiting_top', 'Waiting Page - Top (Ad 1)'), ('waiting_bottom', 'Waiting Page - Bottom (Ad 2)')], default='waiting_top', help_text='Where this ad unit should be displayed on the site.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Check to enable this ad unit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Unit',
                'verbose_name_plural': 'Ad Units',
                'ordering': ['location', '-created_at'],
            },
        ),
    ]
