# Generated by Django 4.2.13 on 2025-07-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0003_adunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url_title',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
